get translation to work on data-on-text & data-off-text for boolean f…
anomalylabs/boolean-field_type pull request #12
Opened 2016-09-16 07:13 UTC by aldf

…ield type

2016-09-16 15:49 UTC, RyanThompson commented on resources/views/switch.twig
> +            data-off-text="{{ trans(field_type.config.off_text ? 'anomaly.field_type.boolean::choice.no' : field_type.config.on_text) }}"
These are backwards. This should use the config text if available - otherwise fallback to the trans string.

2016-09-16 15:50 UTC, RyanThompson requested changes
Little bit of a logic issue here - the trans ternary is backwards.

2016-09-17 12:37 UTC, aldf commented on resources/views/switch.twig
> +            data-off-text="{{ trans(field_type.config.off_text ? 'anomaly.field_type.boolean::choice.no' : field_type.config.on_text) }}"
Correct ,but that won't  display switch button translation for on and off ,i tried to but theme in backwards, it only display YES and NO , no matter the local language you chose

2016-09-18 05:26 UTC, RyanThompson commented
This had the value in the config array on the field type: https://github.com/anomalylabs/boolean-field_type/commit/86b720489c1802d9b64d94583ebd107c4b3614af

2016-09-18 05:27 UTC, closed without merging